name: money_management_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.1.0
  lottie: ^2.6.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^5.4.0
  cloud_firestore: ^4.9.3
  flutter_facebook_auth: ^6.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  rounded_loading_button: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/animation/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
